@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.leviathanstudio.craftstudio;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
